baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'MetaMorph'
theme = 'hugo-flex'

[params]
  footer = ""
  color = "#2C3E50"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "Участники"
pageRef = "/team"
weight = 1

[[menu.main]]
name = "О проекте"
pageRef = "/about"
weight = 2

[[menu.main]]
name = "Ресурсы"
pageRef = "/resourses"
weight = 3

[[menu.main]]
name = "Журнал"
pageRef = "/journal"
weight = 4
